### ISSUE TITLE
CLI won't fail if mlcube task returns a python Error

### ISSUE THREAD

**Issue by aristizabal95** [mlcommons/medperf#37]
Medperf currently identifies runtime errors by checking the subprocess exitcode and failing if it is not 0. This won't catch errors caused inside the MLCube, as even though the task fails, MLCube returns exitcode 0.

Example log:
```
2021-12-15 14:35:01,403 | INFO: Running Cube 'xrv_prep': mlcube run --mlcube=/Users/aristizabal-factored/.medperf/cubes/1/mlcube.yaml --task=sanity_check data_path=/Users/aristizabal-factored/.medperf/data/tmp_1639614896/data
2021-12-15 14:35:03,154 | DEBUG: Traceback (most recent call last):
2021-12-15 14:35:03,154 | DEBUG:
2021-12-15 14:35:03,155 | DEBUG: File "check.py", line 51, in <module>
2021-12-15 14:35:03,155 | DEBUG:
2021-12-15 14:35:03,156 | DEBUG: checker = Checker(args.data_path, params["output_datafile"])
2021-12-15 14:35:03,156 | DEBUG:
2021-12-15 14:35:03,157 | DEBUG: File "check.py", line 13, in __init__
2021-12-15 14:35:03,157 | DEBUG:
2021-12-15 14:35:03,158 | DEBUG: self.df = pd.read_csv(self.data_file)
2021-12-15 14:35:03,158 | DEBUG:
2021-12-15 14:35:03,159 | DEBUG: File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 688, in read_csv
2021-12-15 14:35:03,159 | DEBUG:
2021-12-15 14:35:03,160 | DEBUG: return _read(filepath_or_buffer, kwds)
2021-12-15 14:35:03,160 | DEBUG:
2021-12-15 14:35:03,162 | DEBUG: File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 454, in _read
2021-12-15 14:35:03,162 | DEBUG:
2021-12-15 14:35:03,162 | DEBUG: parser = TextFileReader(fp_or_buf, **kwds)
2021-12-15 14:35:03,163 | DEBUG:
2021-12-15 14:35:03,164 | DEBUG: File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 948, in __init__
2021-12-15 14:35:03,164 | DEBUG:
2021-12-15 14:35:03,165 | DEBUG: self._make_engine(self.engine)
2021-12-15 14:35:03,165 | DEBUG:
2021-12-15 14:35:03,167 | DEBUG: File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 1180, in _make_engine
2021-12-15 14:35:03,167 | DEBUG:
2021-12-15 14:35:03,168 | DEBUG: self._engine = CParserWrapper(self.f, **self.options)
2021-12-15 14:35:03,168 | DEBUG:
2021-12-15 14:35:03,169 | DEBUG: File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 2010, in __init__
2021-12-15 14:35:03,170 | DEBUG:
2021-12-15 14:35:03,170 | DEBUG: self._reader = parsers.TextReader(src, **kwds)
2021-12-15 14:35:03,170 | DEBUG:
2021-12-15 14:35:03,171 | DEBUG: File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
2021-12-15 14:35:03,172 | DEBUG:
2021-12-15 14:35:03,172 | DEBUG:
2021-12-15 14:35:03,173 | DEBUG: File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
2021-12-15 14:35:03,173 | DEBUG:
2021-12-15 14:35:03,175 | DEBUG: FileNotFoundError: [Errno 2] No such file or directory: '/mlcube_io0/data/data.csv'
2021-12-15 14:35:03,175 | DEBUG:
2021-12-15 14:35:03,505 | DEBUG: Cube processes returned 0
```

**Comment by aristizabal95** [comment]
This has been reported to the MLCube team, and they'll see how they can propagate exit status / termination status so it can be detected by Medperf

**Comment by aristizabal95** [comment]
MLCube v0.0.6 fixes this issue
