### ISSUE TITLE
Benchmark ls is failing when getting user benchmarks

### ISSUE THREAD

**Issue by aristizabal95** [mlcommons/medperf#95]

**Comment by aristizabal95** [comment]
At the time of creating this issue I didn't have much information about what conditions caused this error. I wasn't able to reproduce locally

**Comment by hasan7n** [comment]
The error was:
```
MedPerf 0.0.0
Traceback (most recent call last):
  File "/home/hasan/anaconda3/envs/medperf3.9/bin/medperf", line 33, in <module>
    sys.exit(load_entry_point('medperf', 'console_scripts', 'medperf')())
  File "/home/hasan/anaconda3/envs/medperf3.9/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/hasan/anaconda3/envs/medperf3.9/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/hasan/anaconda3/envs/medperf3.9/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/hasan/anaconda3/envs/medperf3.9/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hasan/anaconda3/envs/medperf3.9/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hasan/anaconda3/envs/medperf3.9/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hasan/anaconda3/envs/medperf3.9/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/hasan/anaconda3/envs/medperf3.9/lib/python3.9/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/hasan/Desktop/tasks/medperf/cli/medperf/commands/benchmark/benchmark.py", line 24, in list
    BenchmarksList.run(comms, ui, all)
  File "/home/hasan/Desktop/tasks/medperf/cli/medperf/commands/benchmark/list.py", line 26, in run
    for bmark in benchmarks:
TypeError: 'NoneType' object is not iterable
```


This issue was resolved by [this commit](https://github.com/mlcommons/medperf/commit/2a65709a51a48b94db719b9e9f9a780eb1abdc59).

Tracing back the bug's origin, the return statement was mistakenly removed during [this merge request](https://github.com/mlcommons/medperf/commit/73dbb9c76dc1491edb044473f5f9b2367a4963b1#diff-98dc64738b78d61039b3338da05d8a91f956b47dbe58d45aa17da76ee7e60c6e). It turns out that since then the function `upload_benchmark` (within the same file `rest.py`) is also affected: it returns `None` while it should return the benchmark id. It is not causing issues now but should be fixed to avoid future bugs.
